In [1]:
import pandas as pd
import numpy as np

data = {'a': [1, 2, 3], 'b': [3, 4, 5], 'c': [5, 6, 7]}
df = pd.DataFrame(data)
df

   a  b  c
0  1  3  5
1  2  4  6
2  3  5  7

In [ ]:
ar = np.random.rand(9).reshape(3, 3)
df1 = pd.DataFrame(ar)
df2 = pd.DataFrame(ar, index=['a', 'b', 'c'], columns=['one', 'two', 'three'])  # 可以尝试一下index或columns长度不等于已有数组的情况
df2

In [ ]:
# 选择行与列

df = pd.DataFrame(np.random.rand(12).reshape(3, 4) * 100, index=['one', 'two', 'three'], columns=['a', 'b', 'c', 'd'])
print(df)

data1 = df[['a']]
data2 = df[['a', 'c']]
print(data1, type(data1))
print(data2, type(data2))
print('-----')
# 按照列名选择列，只选择一列输出Series，选择多列输出Dataframe

data3 = df.loc[['one']]
data4 = df.loc[['one', 'two']]
print(data3, type(data3))
print(data4, type(data4))
# 按照index选择行，只选择一行输出Series，选择多行输出Dataframe

In [ ]:
df = pd.DataFrame(np.random.rand(12).reshape(3, 4) * 100, index=['one', 'two', 'three'], columns=['a', 'b', 'c', 'd'])
df

In [ ]:
data1 = df['a']
print(data1, type(data1))
data2 = df[['a', 'c']]
print(data2, type(data2))
data2

In [9]:
data = {'name': ['Jack', 'Mary', 'Tom'], 'age': [18, 22, 26], 'gender': ['male', 'female', 'male']}
df = pd.DataFrame(data, index=['a', 'b', 'c'])
df

   name  age  gender
a  Jack   18    male
b  Mary   22  female
c   Tom   26    male

In [ ]:
data1 = df[['name']]
print(data1, type(data1))
data1

In [ ]:
data2 = df[['name', 'age']]
print(data2, type(data2))
data2

In [58]:
data3 = df[1:]
data3

   name  age  gender
b  Mary   22  female
c   Tom   26    male

In [17]:
data4 = df.loc[0:1]
data4

   name  age  gender
0  Jack   18    male
1  Mary   22  female

In [7]:
data5 = df.iloc[0:2]
data5

   name  age  gender
a  Jack   18    male
b  Mary   22  female

In [10]:
data6 = df.iloc[[1, 0, 2]]
data6

   name  age  gender
b  Mary   22  female
a  Jack   18    male
c   Tom   26    male

In [24]:
data7 = df.iloc[0:2, 0:2]
data7

   name  age
a  Jack   18
b  Mary   22

In [25]:
data8 = df.iloc[[0,2], [0,2]]
data8

   name gender
a  Jack   male
c   Tom   male

In [ ]:
df1 = df[df['age'] > 20]
df1

   name  age  gender
b  Mary   22  female
c   Tom   26    male

In [32]:
df2 = df[df['gender'] == 'male']
df2

   name  age gender
a  Jack   18   male
c   Tom   26   male

In [34]:
df3 = df[(df['gender'] == 'male') & (df['age'] > 20)]
df3

  name  age gender
c  Tom   26   male

In [13]:
df1 = df[['name', 'gender']].iloc[[0, 2]]
df1

   name gender
a  Jack   male
c   Tom   male

In [15]:
df1 = df[['name', 'gender']].loc[['a', 'c']]
df1

   name gender
a  Jack   male
c   Tom   male

In [19]:
df1 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df2 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])
print(df1 + df2)
# DataFrame对象之间的数据自动按照列和索引（行标签）对齐
df1 + df2

          A         B         C   D
0  0.820343 -0.139527 -1.128923 NaN
1  0.150942 -0.402964  2.373046 NaN
2 -0.719896 -0.326867 -1.500015 NaN
3  2.985675  1.916593  0.191451 NaN
4  1.372835 -1.663137 -0.201833 NaN
5 -0.908226  1.189947 -0.266061 NaN
6 -0.832923 -0.751559 -1.483326 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

          A         B         C   D
0  0.820343 -0.139527 -1.128923 NaN
1  0.150942 -0.402964  2.373046 NaN
2 -0.719896 -0.326867 -1.500015 NaN
3  2.985675  1.916593  0.191451 NaN
4  1.372835 -1.663137 -0.201833 NaN
5 -0.908226  1.189947 -0.266061 NaN
6 -0.832923 -0.751559 -1.483326 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN