In [28]:
import pandas as pd
import numpy as np

df = pd.read_excel("scores.xlsx")
df

    班级    姓名         学号   语文   数学    英语  物理   化学   生物
0    1   贾婧瑜  202460101  109  126  81.5  55   93   96
1    1   李东泽  202460102  118  113  51.0  63   96   98
2    1   王子涵  202460104  105   73  51.0  61   99  100
3    1   张乘瑞  202460111   88  107  38.0  57  100   91
4    1   任玉莹  202460106  103   86  75.0  46   89   85
..  ..   ...        ...  ...  ...   ...  ..  ...  ...
72   3   黄琬婷  202440217   87   34  40.5  33   58   42
73   3   宋鑫淼  202440313   88   20  33.0  16   48   56
74   3   杨皓鑫  202440307   69   34  37.5  14   48   58
75   3   刘昌林  202440318   15   19  42.0  10   58   41
76   3  董吴议泽  202440317    0    0  27.0   0   30   48

[77 rows x 9 columns]

In [2]:
df.head(3)

   班级   姓名         学号   语文   数学    英语  物理  化学   生物
0   1  贾婧瑜  202460101  109  126  81.5  55  93   96
1   1  李东泽  202460102  118  113  51.0  63  96   98
2   1  王子涵  202460104  105   73  51.0  61  99  100

In [4]:
data = {'name': ['Jack', 'Mary', 'Tom'], 'age': [18, 22, 26], 'gender': ['male', 'female', 'male']}
df = pd.DataFrame(data, index=['a', 'b', 'c'])
df.T

           a       b     c
name    Jack    Mary   Tom
age       18      22    26
gender  male  female  male

In [7]:
df['体育'] = 100
df.head()

   班级   姓名         学号   语文   数学    英语  物理   化学   生物   体育
0   1  贾婧瑜  202460101  109  126  81.5  55   93   96  100
1   1  李东泽  202460102  118  113  51.0  63   96   98  100
2   1  王子涵  202460104  105   73  51.0  61   99  100  100
3   1  张乘瑞  202460111   88  107  38.0  57  100   91  100
4   1  任玉莹  202460106  103   86  75.0  46   89   85  100

In [9]:
df.loc[77] = 100
df.tail()

     班级    姓名         学号   语文   数学     英语   物理   化学   生物   体育
73    3   宋鑫淼  202440313   88   20   33.0   16   48   56  100
74    3   杨皓鑫  202440307   69   34   37.5   14   48   58  100
75    3   刘昌林  202440318   15   19   42.0   10   58   41  100
76    3  董吴议泽  202440317    0    0   27.0    0   30   48  100
77  100   100        100  100  100  100.0  100  100  100  100

In [14]:
# del df['学号']
df.head()

   班级   姓名   语文   数学    英语  物理   化学   生物   体育
0   1  贾婧瑜  109  126  81.5  55   93   96  100
1   1  李东泽  118  113  51.0  63   96   98  100
2   1  王子涵  105   73  51.0  61   99  100  100
3   1  张乘瑞   88  107  38.0  57  100   91  100
4   1  任玉莹  103   86  75.0  46   89   85  100

In [ ]:
# 删除标签为77的行
df = df.drop(index=77)
# 删除列名为'生物'和'体育'的列
df = df.drop(columns=['生物', '体育'])
df

    班级    姓名   语文   数学    英语  物理   化学
0    1   贾婧瑜  109  126  81.5  55   93
1    1   李东泽  118  113  51.0  63   96
2    1   王子涵  105   73  51.0  61   99
3    1   张乘瑞   88  107  38.0  57  100
4    1   任玉莹  103   86  75.0  46   89
..  ..   ...  ...  ...   ...  ..  ...
72   3   黄琬婷   87   34  40.5  33   58
73   3   宋鑫淼   88   20  33.0  16   48
74   3   杨皓鑫   69   34  37.5  14   48
75   3   刘昌林   15   19  42.0  10   58
76   3  董吴议泽    0    0  27.0   0   30

[77 rows x 7 columns]

In [ ]:
df = df.drop(77)
# # axis=1表示删除列，默认为0表示删除行
df = df.drop(['生物', '体育'], axis=1)

In [36]:
df = df.sort_values('语文', ascending=False)
df.head()

   班级   姓名   语文   数学     英语  物理  化学  生物
1   1  李东泽  118  113   51.0  63  96  98
7   1  王馨冉  113   92   41.0  37  85  91
6   1  张宇馨  112   78   73.0  36  84  86
0   1  贾婧瑜  109  126   81.5  55  93  96
5   1  张子辰  108   64  100.5  36  86  81

In [40]:
df = df.sort_values(['班级', '化学'], ascending=[True, False])
df.head()

    班级   姓名   语文   数学    英语  物理   化学   生物
3    1  张乘瑞   88  107  38.0  57  100   91
2    1  王子涵  105   73  51.0  61   99  100
11   1  刘芳妤    0   92  49.5  52   97  100
1    1  李东泽  118  113  51.0  63   96   98
0    1  贾婧瑜  109  126  81.5  55   93   96

班级      1
姓名    于国胜
语文      0
数学      0
英语    0.0
物理      0
化学      0
生物      0
dtype: object