In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv('test.csv', sep=',', encoding='gbk')
df

   0.560268  -0.559426  1.176857  0.885549
0  2.396094  -0.720063 -1.144393 -0.149686
1  0.036016  -1.032553  0.526661  0.524164
2  0.120952  -0.495401 -0.006828 -2.375663
3  1.125484   0.685709 -0.144614 -0.398538
4 -0.027859   0.331943 -1.256073 -0.659318

In [9]:
df = pd.read_csv('test.csv', sep=',', encoding='gbk', header=None, names=['A', 'B', 'C', 'D'])
df

          A         B         C         D
0  0.560268 -0.559426  1.176857  0.885549
1  2.396094 -0.720063 -1.144393 -0.149686
2  0.036016 -1.032553  0.526661  0.524164
3  0.120952 -0.495401 -0.006828 -2.375663
4  1.125484  0.685709 -0.144614 -0.398538
5 -0.027859  0.331943 -1.256073 -0.659318

In [17]:
df = pd.read_excel('data.xlsx', header=None, names=['A', 'B', 'C', 'D'])
df

          A         B         C         D
0  0.560268 -0.559426  1.176857  0.885549
1  2.396094 -0.720063 -1.144393 -0.149686
2  0.036016 -1.032553  0.526661  0.524164
3  0.120952 -0.495401 -0.006828 -2.375663
4  1.125484  0.685709 -0.144614 -0.398538
5 -0.027859  0.331943 -1.256073 -0.659318

In [22]:
df = pd.read_excel('data.xlsx', sheet_name=1)
df

   班级   姓名   语文   数学    英语  物理  化学   生物
0   1  贾婧瑜  109  126  81.5  55  93   96
1   1  李东泽  118  113  51.0  63  96   98
2   1  王子涵  105   73  51.0  61  99  100

In [21]:
df = pd.read_excel('data.xlsx', sheet_name=None)
df

{'Sheet1':     0.560268  -0.559426   1.176857   0.885549
 0   2.396094  -0.720063  -1.144393  -0.149686
 1   0.036016  -1.032553   0.526661   0.524164
 2   0.120952  -0.495401  -0.006828  -2.375663
 3   1.125484   0.685709  -0.144614  -0.398538
 4  -0.027859   0.331943  -1.256073  -0.659318,
 'Sheet2':    班级   姓名   语文   数学    英语  物理  化学   生物
 0   1  贾婧瑜  109  126  81.5  55  93   96
 1   1  李东泽  118  113  51.0  63  96   98
 2   1  王子涵  105   73  51.0  61  99  100}

In [27]:
df = pd.read_excel('data.xlsx', sheet_name=1)
df.to_csv('data.csv', encoding='gbk')

In [30]:
df = pd.read_csv('data.csv', sep=',', encoding='gbk')
df

   Unnamed: 0  班级   姓名   语文   数学    英语  物理  化学   生物
0           0   1  贾婧瑜  109  126  81.5  55  93   96
1           1   1  李东泽  118  113  51.0  63  96   98
2           2   1  王子涵  105   73  51.0  61  99  100

In [34]:
df = pd.read_excel('data.xlsx', sheet_name=1)
df.to_csv('data.csv', encoding='gbk', index=False)

In [38]:
df = pd.read_excel('data.xlsx', sheet_name=1)
df.to_csv('data.csv', encoding='gbk', index=False)
df2 = pd.read_excel('data.xlsx', sheet_name=2)
df2.to_csv('data.csv', encoding='gbk', index=False, mode='a', header=False)

In [40]:
df = pd.read_csv('test.csv', sep=',', encoding='gbk', header=None, names=['A', 'B', 'C', 'D'])
df.to_excel('test.xlsx', index=False, header=False)