In [22]:
import pandas as pd
import numpy as np

df = pd.read_excel("scores.xlsx")
df

    班级    姓名         学号   语文   数学    英语  物理   化学   生物
0    1   贾婧瑜  202460101  109  126  81.5  55   93   96
1    1   李东泽  202460102  118  113  51.0  63   96   98
2    1   王子涵  202460104  105   73  51.0  61   99  100
3    1   张乘瑞  202460111   88  107  38.0  57  100   91
4    1   任玉莹  202460106  103   86  75.0  46   89   85
..  ..   ...        ...  ...  ...   ...  ..  ...  ...
72   3   黄琬婷  202440217   87   34  40.5  33   58   42
73   3   宋鑫淼  202440313   88   20  33.0  16   48   56
74   3   杨皓鑫  202440307   69   34  37.5  14   48   58
75   3   刘昌林  202440318   15   19  42.0  10   58   41
76   3  董吴议泽  202440317    0    0  27.0   0   30   48

[77 rows x 9 columns]

In [23]:
df['总分'] = df[['语文', '数学', '英语', '物理', '化学', '生物']].sum(axis=1)
df

    班级    姓名         学号   语文   数学    英语  物理   化学   生物     总分
0    1   贾婧瑜  202460101  109  126  81.5  55   93   96  560.5
1    1   李东泽  202460102  118  113  51.0  63   96   98  539.0
2    1   王子涵  202460104  105   73  51.0  61   99  100  489.0
3    1   张乘瑞  202460111   88  107  38.0  57  100   91  481.0
4    1   任玉莹  202460106  103   86  75.0  46   89   85  484.0
..  ..   ...        ...  ...  ...   ...  ..  ...  ...    ...
72   3   黄琬婷  202440217   87   34  40.5  33   58   42  294.5
73   3   宋鑫淼  202440313   88   20  33.0  16   48   56  261.0
74   3   杨皓鑫  202440307   69   34  37.5  14   48   58  260.5
75   3   刘昌林  202440318   15   19  42.0  10   58   41  185.0
76   3  董吴议泽  202440317    0    0  27.0   0   30   48  105.0

[77 rows x 10 columns]

In [17]:
average_row = df.mean(numeric_only=True)

In [27]:
# 创建包含重复值的Series
s = pd.Series(['A', 'B', 'A', 'C', 'B', 'D'])
unique_values = s.unique()
print(unique_values)  # 输出：['A' 'B' 'C' 'D']
print(type(unique_values))  # 输出：<class 'numpy.ndarray'>

['A' 'B' 'C' 'D']
<class 'numpy.ndarray'>

In [33]:
df['化学'].value_counts(bins=[0, 60, 80, 90, 100])  # 按成绩分组统计

化学
(60.0, 80.0]      29
(-0.001, 60.0]    25
(80.0, 90.0]      16
(90.0, 100.0]      7
Name: count, dtype: int64

In [ ]:
Series.value_counts(
    normalize=False,   # 是否返回频率（比例）而非计数
    sort=True,         # 是否按值排序
    ascending=False,   # 是否升序排列
    bins=None,         # 对数值型数据分箱统计
    dropna=True        # 是否排除缺失值（NaN）
)

In [35]:
print(df['化学'].describe())

count     77.000000
mean      68.571429
std       18.841045
min        0.000000
25%       58.000000
50%       70.000000
75%       81.000000
max      100.000000
Name: 化学, dtype: float64

In [37]:
print(df['化学'].replace(0, np.nan).mean())

70.4

In [ ]:
df = df.replace(0, np.nan)
average_score = df[['语文', '数学', '英语', '物理', '化学', '生物']].mean()
print(average_score)

语文    86.878378
数学    52.453333
英语    49.340000
物理    30.133333
化学    70.400000
生物    74.120000
dtype: float64

In [ ]:
df = df.replace(0, np.nan)
class_average = df.groupby('班级')[['语文', '数学', '英语', '物理', '化学', '生物']].mean()
print(class_average)

           语文         数学         英语         物理         化学         生物
班级
1   98.259259  66.285714  55.785714  37.678571  83.178571  81.357143
2   82.714286  39.892857  43.851852  25.500000  65.851852  72.592593
3   76.842105  50.578947  47.725000  25.842105  58.650000  66.050000