In [1]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

# 创建示例问卷数据（假设数据存储在CSV文件中）
data = {"性别": ["男", "女", "女", "男", "女", "男", "女"], "年龄组": ["18-25", "26-35", "18-25", "36-45", "26-35", "18-25", "36-45"], "满意度": ["满意", "非常满意", "一般", "不满意", "满意", "满意", "一般"]}
df = pd.DataFrame(data)

# 统计单选项（如性别、满意度）
print("性别分布：")
print(df["性别"].value_counts())

print("\n满意度分布：")
print(df["满意度"].value_counts(normalize=True))

性别分布：
性别
女    4
男    3
Name: count, dtype: int64

满意度分布：
满意度
满意      0.428571
一般      0.285714
非常满意    0.142857
不满意     0.142857
Name: proportion, dtype: float64

In [15]:
print(df["满意度"].value_counts(normalize=True).loc[["非常满意", "满意", "一般", "不满意"]])

满意度
非常满意    0.142857
满意      0.428571
一般      0.285714
不满意     0.142857
Name: proportion, dtype: float64

In [19]:
df["满意度"].isin(["满意", "非常满意"])

0     True
1     True
2    False
3    False
4     True
5     True
6    False
Name: 满意度, dtype: bool

In [18]:
df[df["满意度"].isin(["满意", "非常满意"])]

  性别    年龄组   满意度
0  男  18-25    满意
1  女  26-35  非常满意
4  女  26-35    满意
5  男  18-25    满意

In [ ]:
df[df["城市"].isin(["北京", "上海"]) & (df["销售额"] > 10000)]
df_holiday_sales = df[df["日期"].isin(["2025-01-01", "2025-02-18"])]

In [ ]:
df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'], 'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3']})
df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'], 'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']})
df3 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'], 'key2': ['K0', 'K1', 'K0', 'K1'], 'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3']})
df4 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'], 'key2': ['K0', 'K0', 'K0', 'K0'], 'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']})
print(pd.merge(df1, df2, on='key'))
print('------')
# left：第一个df
# right：第二个df
# on：参考键

print(pd.merge(df3, df4, on=['key1', 'key2']))
df4

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3
------
  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [ ]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'], columns=['one', 'two', 'three'])

df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

df

        one       two     three
a  0.398696  0.179553  0.279735
b       NaN       NaN       NaN
c -0.033794  0.460356  1.135415
d       NaN       NaN       NaN
e -1.525358  0.545561  0.914649
f  0.547017 -1.004220 -0.685609
g       NaN       NaN       NaN
h  0.247076 -0.769030 -0.582242

In [26]:
print(df.isnull())

     one    two  three
a  False  False  False
b   True   True   True
c  False  False  False
d   True   True   True
e  False  False  False
f  False  False  False
g   True   True   True
h  False  False  False

In [28]:
df.dropna()

        one       two     three
a  0.398696  0.179553  0.279735
c -0.033794  0.460356  1.135415
e -1.525358  0.545561  0.914649
f  0.547017 -1.004220 -0.685609
h  0.247076 -0.769030 -0.582242

In [34]:
df.fillna(0)  # 全局填充为0
df.fillna(df.mean())  # 按列均值填充
df.fillna(method='ffill')  # 前一个有效值填充
df.fillna(method='bfill')  # 后一个有效值填充

        one       two     three
a  0.398696  0.179553  0.279735
b -0.033794  0.460356  1.135415
c -0.033794  0.460356  1.135415
d -1.525358  0.545561  0.914649
e -1.525358  0.545561  0.914649
f  0.547017 -1.004220 -0.685609
g  0.247076 -0.769030 -0.582242
h  0.247076 -0.769030 -0.582242