In [3]:
import pandas as pd
df = pd.DataFrame({
    '班级': [1, 1, 2, 2],
    '科目': ['语文', '数学', '语文', '数学'],
    '分数': [90, 85, 88, 92]
})
pivot_df = df.pivot(index='班级', columns='科目', values='分数')
df

   班级  科目  分数
0   1  语文  90
1   1  数学  85
2   2  语文  88
3   2  数学  92

In [6]:
pivot_df

科目  数学  语文
班级
1   85  90
2   92  88